name        'garethr-scala'
version     '0.1.2'
source      'git://github.com/garethr/garethr-scala.git'
author      'Gareth Rushgrove'
summary     'Module for installing typesafe scala'
description 'Install scala, sbt and gt8 from the typesafe scala apt repository'
license     'Apache License, Version 2.0'
dependency  'maestrodev/wget'
dependency  'puppetlabs/stdlib'
